### ISSUE TITLE
Travis - Linux Chrome driver doesn't start

### ISSUE THREAD

**Issue by thomasam97** [sprinteins/ghost#61] opened 2019-07-29 08:52 UTC
The Linux jobs fail due to the above mentioned error
Copied error message:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ghost@1.0.2 test: `npm run build &&mocha --exit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Ghost@1.0.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-07-29T08_43_49_381Z-debug.log
The command "if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm run test; else npm run test; fi" exited with 1.

**Comment by L4B0MB4** [comment] 2019-07-29 09:51
@N3ol4N should we continue merging pull requests after local testing or should we wait until we fixed this problem ?

**Comment by L4B0MB4** [comment] 2019-07-30 11:43
As I am moving and currently have no internet connection, I will probably not be able to look at it for this week (at least)

**Comment by L4B0MB4** [comment] 2019-08-04 09:56
Sorry for spamming the pull request, but travis doenst find my test repository. I already contacted the travis support.

**Comment by N3ol4N** [comment] 2019-08-05 08:05
for now, the mac os tests seem to be fine with travis. in the current state i'd say, we still commit and merge as long as the mac os tests are fine, so we don't stop the overall project.
but in the meantime it would be much appreciated, if you could keep up locking for a fix on the linux issues of travis.

**Comment by L4B0MB4** [comment] 2019-08-05 17:41
I´ll work on it 👍

**Comment by L4B0MB4** [comment] 2019-08-10 08:59
https://github.com/features/actions this might be intresting too

**Comment by L4B0MB4** [comment] 2019-08-12 06:15
I set up a virtual machine with ubuntu 18.x and I was not able to reproduce this behaviour

**Comment by L4B0MB4** [comment] 2019-08-12 07:21
This will be fixed with:  #60

**Closed by L4B0MB4** 2019-08-12 07:21 UTC
Labels: bug
